#!/usr/bin/env bash


FORMAT_PATH="${HOME}/.config/i3blocks/state/date_format"

format="$(cat "${FORMAT_PATH}")"
if [ "${BLOCK_BUTTON}" = "1" ]; then
    if [ "${format:0:1}" == "1" ]; then
	format=0${format:1:1}
    else
	format=1${format:1:1}
    fi
    echo $format | tee "${FORMAT_PATH}" &> /dev/null
elif [ "${BLOCK_BUTTON}" = "3" ]; then
    if [ "${format:1:1}" == "1" ]; then
	format=${format:0:1}0
    else
	format=${format:0:1}1
    fi
    echo $format | tee "${FORMAT_PATH}" &> /dev/null
fi


if [ "$format" = 00 ]; then
    date_format="%b %-d"
elif [ "$format" = 01 ]; then
    date_format="%b %-d: %a"
elif [ "$format" = 10 ]; then
    date_format="%-m/%-d"
else
    date_format="%-m/%-d: %u"
fi

echo $(date "+$date_format")
echo $(date "+$date_format")
echo "#A4AEB3"

