#!/usr/bin/env bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

echo ' '
echo ' '

interface="${BLOCK_INSTANCE:-$(iw dev | grep -m 1 '^\s*Interface .*$' | sed 's/\s*Interface //')}"

if [[ -d /sys/class/net/${interface}/wireless ]]; then
    if [[ "$(cat /sys/class/net/${interface}/operstate)" = 'down' ]]; then
        echo '#A4AEB3'
        exit 0
    fi
fi


quality=$(grep $interface /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

if [[ $quality -ge 80 ]]; then
    echo "#5AE234"
elif [[ $quality -ge 60 ]]; then
    echo "#FCE94F"
elif [[ $quality -ge 40 ]]; then
    echo "#FFA12F"
elif [[ $quality -ge 20 ]]; then
    echo "#FF2236"
fi


exit 0
