#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

source $HOME/.aliases

export PATH="${HOME}/bin:${PATH}"
export PATH="${HOME}/.config/i3/bin:${PATH}"
