#!/bin/sh

# Load X11 resource settings.
xrdb "${HOME}/.Xresources"

# Use caps lock as an additional super key.
# Use windows key as an additional ctrl key.
# Use shift + right shift as an additional caps lock.
setxkbmap -option
setxkbmap -option caps:super #,altwin:ctrl_win,shift:both_capslock

# Apply other key mappings.
xmodmap "${HOME}/.Xmodmap"

# Set the keyboard repeat rate.
xset r rate 300 25

# Set up monitors.
#xrandr --output HDMI-1 --off
#xrandr --output DP-2 --mode 1920x1080 --pos 0x0
#xrandr --output DP-3 --mode 1920x1080 --pos 1920x0

# Don't disable the touchpad while a key is pressed.
xinput set-prop 10 348 0
