#!/bin/sh

# Load session settings.
. "${HOME}/.xconfig"

# Run compositor daemon.
picom -b &

# Run blue light filter daemon.
gammastep -m randr -l 36:-115 &

# Run notification daemon.
dunst &

# Run reminder daemon.
#remind -z '-knotify-send -u critical -t 60000 "Reminder: $(date +%H:%M)" %s &' "${HOME}"/.reminders &

# Run terminal daemon.
urxvtd -f -o &

# Set desktop background.
"${HOME}"/.fehbg

# Have Java antialias its fonts & use GTK theme.
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

# Activate IBus.
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
