#!/bin/sh

# Use caps lock as additional super key
setxkbmap -option caps:super &

# Apply other key mappings
xmodmap "${HOME}/.Xmodmap" &

# Set keyboard repeat rate
xset r rate 300 25 &

# Screen locker daemon
light-locker &

# Lock screen after inactivity
xautolock -time 5 -locker "${HOME}/.config/i3/bin/lock" -notify 30 -notifier "notify-send 'Autolock' 'In 30 seconds'" -killtime 2 -killer "systemctl suspend" -secure -detectsleep &

# Notification daemon
dunst &

# Text editor daemon
emacs --daemon &

# Terminal daemon
urxvtd -f -o &

# Compositor
picom -b &

# Desktop background
"${HOME}"/.fehbg &

# Have Java antialias its fonts & use GTK theme
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

# Activate IBus
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
