# Show MOTD
clear
cat "${HOME}/.motd"

# Fix VTE issue
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
source /etc/profile.d/vte.sh
fi

# {{{ Completion (thanks to Frew Schmidt)
# Faster! (?)
zstyle ':completion::complete:*' use-cache 1

# Case insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%F{cyan}%B%d%b%f'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' completer _expand _force_rehash _complete _approximate _ignored

# Generate descriptions with magic.
zstyle ':completion:*' auto-description 'specify: %d'

# Don't prompt for a huge list, page it!
zstyle ':completion:*:default' list-prompt '%S%M matches%s'

# Don't prompt for a huge list, menu it!
zstyle ':completion:*:default' menu 'select=0'

# Have the newer files last so I see them first
zstyle ':completion:*' file-sort modification reverse

# Color code completion
zstyle ':completion:*' list-colors "=(#b) #([0-9]#)*=36=31"

unsetopt LIST_AMBIGUOUS
setopt  COMPLETE_IN_WORD

# Separate man page sections. Neat.
zstyle ':completion:*:manuals' separate-sections true

# Egomaniac!
zstyle ':completion:*' list-separator 'fREW'

# Complete with a menu for xwindow ids
zstyle ':completion:*:windows' menu on=0
zstyle ':completion:*:expand:*' tag-order all-expansions

# More errors allowed for large words and fewer for small words
zstyle ':completion:*:approximate:*' max-errors 'reply=(  $((  ($#PREFIX+$#SUFFIX)/3  ))  )'

zstyle ':completion::approximate*:*' prefix-needed true

# Errors format
zstyle ':completion:*:corrections' format '%F{magenta}%B%d%b%f'

# Don't complete stuff already on the line
zstyle ':completion::*:(rm|vi):*' ignore-line true

# Don't complete directory we are already in (../here)
zstyle ':completion:*' ignore-parents parent pwd

_force_rehash() {
(( CURRENT == 1 )) && rehash
return 1  # Because we didn't really complete anything
}
# }}}

# oh-my-zsh: General
ZSH=/usr/share/oh-my-zsh/
ZSH_CACHE_DIR="${HOME}/.cache/oh-my-zsh"
if [ ! -d "${ZSH_CACHE_DIR}" ]; then
mkdir -p "${ZSH_CACHE_DIR}"
fi

# oh-my-zsh: Configuration
ZSH_THEME=
HYPHEN_INSENSITIVE='true'
export UPDATE_ZSH_DAYS=14
COMPLETION_WAITING_DOTS='false'

# oh-my-zsh: Plugins
plugins=(git)
# Consider:
#
# gitignore
# git-extras
# git-prompt
# taskwarrior
# z
#

# Set up fasd
eval "$(fasd --init auto)"

# oh-my-zsh: Setup
source $ZSH/oh-my-zsh.sh

# Completion
autoload -Uz compinit
compinit -d "${ZSH_CACHE_DIR}/zcompdump-${ZSH_VERSION}"
# autoload bashcompinit
# bashcompinit
# eval "$(pandoc --bash-completion)"

# Save all the history!
HISTFILE=~/.histfile
HISTSIZE=16777216
SAVEHIST=16777216
setopt EXTENDED_HISTORY

# Beeps should notify
setopt beep notify

# Emacs key bindings
bindkey -e

# Aliases
source "${HOME}/.aliases"

# Directory navigation
setopt autopushd
DIRSTACKSIZE=128
cdUndoKey() { dirs -v | grep -q '^1' && popd -q && zle reset-prompt }
cdParentKey() { [ "$(pwd)" != "/" ] && pushd -q .. && zle reset-prompt }
zle -N cdUndoKey
zle -N cdParentKey
bindkey '[D' cdUndoKey
bindkey '[A' cdParentKey

# Prompt
PROMPT='%(?..[%F{1}%B%?%b%f] )%B%F{10}%n%f@%F{10}%m%f%b:%F{14}%(3~;%-1~/…/%1~;%~)%f%B%(!.#.$)%b '
RPROMPT='%(?..:()'

# Syntax highlighting in zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Fuzzy find (fzf)
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

# Pyenv
eval "$(pyenv init -)"
