zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' rehash true
zstyle :compinstall filename '~/.zshrc'

# oh-my-zsh: General
ZSH=/usr/share/oh-my-zsh/
ZSH_CACHE_DIR="${HOME}/.cache/oh-my-zsh"
if [ ! -d $ZSH_CACHE_DIR ]; then
    mkdir -p $ZSH_CACHE_DIR
fi

# oh-my-zsh: Configuration
ZSH_THEME=
HYPHEN_INSENSITIVE='true'
export UPDATE_ZSH_DAYS=14
COMPLETION_WAITING_DOTS='false'

# oh-my-zsh: Plugins
plugins=(git z you-should-use)
# Consider:
#
# gitignore
# git-extras
# git-prompt
# taskwarrior
#

export YSU_MODE=ALL

# oh-my-zsh: Setup
source $ZSH/oh-my-zsh.sh

# Completion
autoload -Uz compinit
compinit

# History
HISTFILE=~/.histfile
HISTSIZE=2048
SAVEHIST=4096

# Beeps should notify
setopt beep notify

# Emacs key bindings
bindkey -e

# Aliases
source "${HOME}/.aliases"

# Directory navigation
setopt autopushd
DIRSTACKSIZE=128
cdUndoKey() { dirs -v | grep -q '^1' && popd -q && zle reset-prompt }
cdParentKey() { [ "$(pwd)" != "/" ] && pushd -q .. && zle reset-prompt }
zle -N cdUndoKey
zle -N cdParentKey
bindkey '[D' cdUndoKey
bindkey '[A' cdParentKey

# Prompt
PROMPT='%(?..[%F{1}%B%?%b%f] )%B%F{10}%n%f@%F{10}%m%f%b:%F{14}%(3~;%-1~/…/%1~;%~)%f%B%(!.#.$)%b '
RPROMPT='%(?..:()'

# Syntax highlighting in zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
