#!/usr/bin/env bash

set -eu
# set -x

usage() {
    printf "Usage: $0 [option | image-name]

Description: Dotfile wallpaper manager.

Available commands:

    No args
      + Print the current wallpaper

    <image-name>
      + Set the wallpaper to <image-name>

    -h or --help
      + Show this help
    -l or --list
      + List the available wallpapers
"
    exit 1
}

[ $# -le 1 ] || usage


wp_path="${HOME}/.wallpaper"
wp_dir="${HOME}/data/image/walls"

if [ $# -eq 0 ]; then
    basename "$(readlink "$wp_path")"
    exit 0
fi

case $1 in
    -h|--help)
        usage
        exit 0
        ;;
    -l|--list)
        ls -A "$wp_dir"
        ;;
    *)
        if [ ! -f "${wp_dir}/$1" ]; then
            echo 'Image could not be found.'
            echo 'Use -l for a list of options'
            exit 1
        else
            ln -srf "${wp_dir}/$1" "$wp_path"
            feh --bg-fill "${HOME}/.wallpaper"
        fi
esac

exit 0
