#!/usr/bin/env bash

set -eu
# set -x

usage() {
    printf "Usage: $0 [option | image-name]

Description: Dotfile wallpaper manager.

Available commands:

    No args
      + Print the current wallpaper

    <image-name>
      + Set the wallpaper to <image-name>

    -h or --help
      + Show this help
    -l or --list
      + List the available wallpapers
"
    exit 1
}

[ $# -le 1 ] || usage


WP_PATH="${HOME}/.wallpaper"
WP_DIR="${HOME}/data/image/walls"

if [ $# -eq 0 ]; then
    basename "$(readlink "$WP_PATH")"
    exit 0
fi

case $1 in
    -h|--help)
        usage
        exit 0
        ;;
    -l|--list)
        ls -A "$WP_DIR"
        ;;
    *)
        if [ ! -f "${WP_DIR}/$1" ]; then
            echo "Image could not be found."
            echo "Use "\`"$0 -l"\`" for a list of options"
            exit 1
        else
            ln -srf "${WP_DIR}/$1" "$WP_PATH"
            eval "${HOME}/.fehbg"
        fi
esac

exit 0
