#!/bin/sh

# Link configs
dot-glue --link lightdm.conf /etc/lightdm/lightdm.conf
dot-glue --link lightdm-gtk-greeter.conf /etc/lightdm/lightdm-gtk-greeter.conf
dot-glue --link lightdm-webkit2-greeter.conf /etc/lightdm/lightdm-webkit2-greeter.conf
sudo chown root:root -R /etc/lightdm
